In [58]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data=pd.read_csv("HousingData.csv")
data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,NaN,36.2

In [59]:
data.isnull().sum()

CRIM       20
ZN         20
INDUS      20
CHAS       20
NOX         0
RM          0
AGE        20
DIS         0
RAD         0
TAX         0
PTRATIO     0
B           0
LSTAT      20
MEDV        0
dtype: int64

In [60]:
data.dropna(inplace=True)

In [61]:
x=data.iloc[:,:-1]
x

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
5,0.02985,0.0,2.18,0.0,0.458,6.430,58.7,6.0622,3,222,18.7,394.12,5.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,0.17783,0.0,9.69,0.0,0.585,5.569,73.5,2.3999,6,391,19.2,395.77,15.10
500,0.22438,0.0,9.69,0.0,0.585,6.027,79.7,2.4982,6,391,19.2,396.90,14.33
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48

In [62]:
y=data.iloc[:,-1]
y

0      24.0
1      21.6
2      34.7
3      33.4
5      28.7
       ...
499    17.5
500    16.8
502    20.6
503    23.9
504    22.0
Name: MEDV, Length: 394, dtype: float64

In [63]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.25,random_state=41)

In [64]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(xtrain,ytrain)

LinearRegression()

In [65]:
y_pred=model.predict(xtest)

In [66]:
y_pred

array([20.98839564,  6.35129529, 21.19842646, 19.82532372, 30.64220937,
       18.00406838, 24.48615378, 19.76926214, 26.56379349,  3.65342497,
        7.92720051, 23.99606069, 19.23951152, 16.04636305, 17.01758724,
       22.2093867 , 21.99677068, 18.7580041 , 16.74630396, 16.9109654 ,
       21.31283536, 24.95713917, 10.88134306, 11.97479659, 32.49814572,
       18.36156907, 14.8977969 , 16.98297365, 16.41588509, 26.84645931,
       17.07603182, 31.55884366, 35.82830429,  9.89965835, 20.7455784 ,
       14.9042678 , 23.64981745, 36.32632973, 34.65091376, 14.56647329,
       21.1253529 , 24.79063641, 19.41254385, 19.97740011, 23.5905997 ,
       28.41975592, 13.90847236, 17.09606554, 36.7359154 , 13.66219039,
       20.13786832, 12.12447119, 12.94584289, 24.78511634, 12.65009282,
       17.13246311, 35.84795897,  8.98111915, 38.46180409, 18.70372278,
       20.68586805, 22.0122774 , 21.40766617, 25.7691754 , 33.2116951 ,
       41.29266374, 16.48640999, 25.59392973, 14.40035082, 14.0241242 ,
       27.42679552, 15.78415794,  9.14411196, 24.16174844, 18.17216829,
       20.56076842, 12.30386068, 28.43230543, 20.5436228 , 24.5622435 ,
       16.830001  ,  8.85725008, 22.17569531, 24.76854393, 25.33728518,
       29.38856161, 17.05628673, 17.57323656, 25.77928064, 27.74419693,
       11.55616705, 33.4010549 , 40.27907439, 34.99385218, 27.29398621,
       25.83280066, 27.6282313 , 25.29011529, 32.26888339])

In [67]:
from sklearn.metrics import r2_score
r2_score(y_pred,ytest)

0.6641735234225699